// src/services/apiService.ts

import apiClient from '../api/axiosConfig'; // Use the interceptor-enhanced client
import Cookies from 'js-cookie';
import { AxiosError, AxiosResponse } from 'axios';

// --- Type Definitions ---

// Token type expected from login
type AuthToken = string;

// User type based on API response


// --- Task Type Definition ---
// Adjust fields based on your backend TaskResource / Task model
export interface Task {
    id: number;
    title: string;
    description?: string;
    status: 'not_started' | 'in_progress' | 'review' | 'completed' | 'cancelled'; // Example statuses
    project_id: number;
    priority?: 'low' | 'medium' | 'high'; // Example priorities
    due_date?: string | null; // API likely sends string date
    assigned_team: string;
    dependent_task_id?: number | null;
    created_at?: string;
    updated_at?: string;
    // Add other relevant fields like priority, assignee_id, etc.
    // priority?: 'low' | 'medium' | 'high';
}

// Payload for creating a new task (omit fields generated by backend)
// Ensure this matches backend validation rules for POST /api/projects/{projectId}/tasks
export type NewTaskPayload = Omit<Task, | 'project_id' | 'title' | 'description' | 'status' | 'due_date' | 'priority' | 'assigned_team' > & {
    // Add any specific fields required only on creation if necessary
};

// Payload for updating a task (use Partial, or define specific updatable fields)
// Ensure this matches backend validation rules for PUT/PATCH /api/tasks/{taskId}
export type UpdateTaskPayload = Partial<Omit<Task, 'id' | 'project_id' | 'created_at' | 'updated_at'>>;


// Structure for Laravel Paginated Responses
interface PaginatedResponse<T> {
    data: T[];
    links: { first: string | null; last: string | null; prev: string | null; next: string | null; };
    meta: { current_page: number; from: number | null; last_page: number; path: string; per_page: number; to: number | null; total: number; };
}


// API Error Structure
interface ApiError {
  message: string;
  errors?: Record<string, string[]>;
}

// --- Authentication Service Functions ---

const getCsrfCookie = async (): Promise<void> => {
  try {
    await apiClient.get('/sanctum/csrf-cookie');
    console.log('CSRF cookie fetched');
  } catch (error) {
    const axiosError = error as AxiosError<ApiError>;
    console.error('Error fetching CSRF cookie:', axiosError.response?.data?.message || axiosError.message);
    throw error;
  }
};


// --- Task Service Functions ---
//fetch all tasks by the user
const getAllTasks = async (): Promise<Task[]> => {
    // Interceptor adds Bearer token
    try {
        const response = await apiClient.get<PaginatedResponse<Task>>('/api/tasks/allTasks'); // Adjust endpoint as needed
        console.log('All tasks fetched:', response.data);
        return response.data; // Return the actual tasks array
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error('Failed to fetch all tasks:', axiosError.response?.data || axiosError.message);
        throw error; // Re-throw to be handled by caller
    }
};
/**
 * Fetches tasks for a specific project. Assumes API endpoint returns paginated tasks.
 * @param projectId The ID of the project whose tasks are to be fetched.
 * @returns Promise<Task[]> An array of tasks for the project.
 */
const getTasksForProject = async (projectId: number): Promise<Task[]> => {
    // Interceptor adds Bearer token
    try {
        // Assuming the endpoint returns a paginated response for tasks within a project
        const response = await apiClient.get<PaginatedResponse<Task>>(`api/tasks/${projectId}/index`);
        console.log(`Tasks fetched for project ${projectId}:`, response.data);
        return response.data || []; // Return the actual tasks array
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error(`Failed to fetch tasks for project ${projectId}:`, axiosError.response?.data || axiosError.message);
        throw error; // Re-throw to be handled by caller
    }
};

/**
 * Creates a new task for a specific project.
 * @param projectId The ID of the project to add the task to.
 * @param payload The data for the new task (matching NewTaskPayload).
 * @returns Promise<Task> The newly created task data from the API.
 */
const createTaskForProject = async (projectId: number, payload: NewTaskPayload): Promise<Task> => {
    const xsrfToken = Cookies.get('XSRF-TOKEN');
    console.log(payload);
    try {
        payload.project_id = projectId; // Ensure the payload has the project ID
        console.log('Payload for creating task:', payload); // Debug log
        const response = await apiClient.post<Task>('/api/tasks/store', payload, {
            headers: { 'X-XSRF-TOKEN': xsrfToken || '' }, // Add if CSRF needed here
        });
        console.log(`Task created for project ${projectId}:`, response.data);
        return response.data; // Return the created task data
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error(`Failed to create task for project ${projectId}:`, axiosError.response?.data || axiosError.message);
        throw error;
    }
};

/**
 * Fetches a single task by its ID.
 * @param taskId The ID of the task to fetch.
 * @returns Promise<Task | null> The task data or null if not found.
 */
const getTaskById = async (taskId: number): Promise<Task | null> => {
    // Interceptor adds Bearer token
    try {
        const response = await apiClient.get<Task>(`/api/tasks/${taskId}`);
        console.log('Task fetched:', response.data);
        return response.data;
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error(`Failed to fetch task ${taskId}:`, axiosError.response?.data || axiosError.message);
        if (axiosError.response?.status === 404) {
            console.log(`Task ${taskId} not found.`);
            return null;
        }
        throw error;
    }
};

/**
 * Updates an existing task.
 * @param taskId The ID of the task to update.
 * @param payload The data to update (matching UpdateTaskPayload).
 * @returns Promise<Task> The updated task data from the API.
 */
const updateTask = async (taskId: number, payload: UpdateTaskPayload): Promise<Task> => {
    // Interceptor adds Bearer token
    // const xsrfToken = Cookies.get('XSRF-TOKEN');
    try {
        // Use PUT or PATCH based on your API design
        const response = await apiClient.post<Task>(`/api/tasks/${taskId}/update`, payload /*, {
            headers: { 'X-XSRF-TOKEN': xsrfToken || '' } // Add if CSRF needed here
        }*/);
        console.log(`Task ${taskId} updated:`, response.data);
        return response.data; // Return the updated task data
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error(`Failed to update task ${taskId}:`, axiosError.response?.data || axiosError.message);
        throw error;
    }
};

/**
 * Deletes a task by its ID.
 * @param taskId The ID of the task to delete.
 * @returns Promise<void>
 */
const deleteTask = async (taskId: number): Promise<void> => {
    // Interceptor adds Bearer token
    // const xsrfToken = Cookies.get('XSRF-TOKEN');
    try {
        // Expecting 204 No Content on successful delete
        await apiClient.delete(`/api/tasks/${taskId}` /*, {
            headers: { 'X-XSRF-TOKEN': xsrfToken || '' } // Add if CSRF needed here
        }*/);
        console.log('Task deleted:', taskId);
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error(`Failed to delete task ${taskId}:`, axiosError.response?.data || axiosError.message);
        throw error;
    }
};
// function to chnage task status to completed
const changeTaskStatus = async (taskId: number, status: 'completed' ): Promise<Task> => {
    // Interceptor adds Bearer token
    const xsrfToken = Cookies.get('XSRF-TOKEN');
    try {
        // Use PUT or PATCH based on your API design
        const response = await apiClient.post<Task>(`/api/tasks/${taskId}/complete`, { status } , {
            headers: { 'X-XSRF-TOKEN': xsrfToken || '' } // Add if CSRF needed here
        });
        console.log(`Task ${taskId} status updated to ${status}:`, response.data);
        return response.data; // Return the updated task data
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error(`Failed to update task ${taskId} status:`, axiosError.response?.data || axiosError.message);
        throw error;
    }
};


// --- Exports ---

export const authService = {
  getCsrfCookie,

};


// --- Export Task Service ---
export const taskService = {
    getTasksForProject,
    createTaskForProject,
    getTaskById,
    updateTask,
    deleteTask,
    getAllTasks,
    changeTaskStatus,
};
// ---------------------------

// Or export all combined if preferred:
// export const apiService = { ...authService, ...projectService, ...taskService };

