// src/services/apiService.ts

import apiClient from '../api/axiosConfig'; // Use the interceptor-enhanced client
import Cookies from 'js-cookie';
import { AxiosError, AxiosResponse } from 'axios';

// --- Type Definitions ---

// Token type expected from login
type AuthToken = string;

// User type based on API response


// --- Task Type Definition ---
// Adjust fields based on your backend TaskResource / Task model
export interface Task {
    id: number;
    title: string;
    description?: string;
    status: 'not_started' | 'in_progress' | 'review' | 'completed' | 'cancelled'; // Example statuses
    project_id: number;
    priority?: 'low' | 'medium' | 'high'; // Example priorities
    due_date?: string | null; // API likely sends string date
    assigned_team?: string | null; // Or team_id if you store that
    dependent_task_id?: number | null;
    created_at?: string;
    updated_at?: string;
    // Add other relevant fields like priority, assignee_id, etc.
    // priority?: 'low' | 'medium' | 'high';
}

// Payload for creating a new task (omit fields generated by backend)
// Ensure this matches backend validation rules for POST /api/projects/{projectId}/tasks
export type NewTaskPayload = Omit<Task, | 'project_id' | 'title' | 'description' | 'status' | 'due_date' | 'priority' | 'assigned_team' > & {
    // Add any specific fields required only on creation if necessary
};

// Payload for updating a task (use Partial, or define specific updatable fields)
// Ensure this matches backend validation rules for PUT/PATCH /api/tasks/{taskId}
export type UpdateTaskPayload = Partial<Omit<Task, 'id' | 'project_id' | 'created_at' | 'updated_at'>>;


// Structure for Laravel Paginated Responses
interface PaginatedResponse<T> {
    data: T[];
    links: { first: string | null; last: string | null; prev: string | null; next: string | null; };
    meta: { current_page: number; from: number | null; last_page: number; path: string; per_page: number; to: number | null; total: number; };
}


// API Error Structure
interface ApiError {
  message: string;
  errors?: Record<string, string[]>;
}

// --- Authentication Service Functions ---

const getCsrfCookie = async (): Promise<void> => {
  try {
    await apiClient.get('/sanctum/csrf-cookie');
    console.log('CSRF cookie fetched');
  } catch (error) {
    const axiosError = error as AxiosError<ApiError>;
    console.error('Error fetching CSRF cookie:', axiosError.response?.data?.message || axiosError.message);
    throw error;
  }
};
// --- Team Type Definitions ---

// Team type based on API response
export interface Team {
    id: number;
    team_name: string;
    description?: string;
    created_at?: string;
    updated_at?: string;
    members?: Array<{ id: number; name: string; email: string }>; // Example member structure
}

// Payload for creating a new team
export type NewTeamPayload = Omit<Team, 'id' | 'created_at' | 'updated_at'>;

// Payload for updating a team
export type UpdateTeamPayload = Partial<Omit<Team, 'id' | 'created_at' | 'updated_at'>>;

// --- Team Service Functions ---

/**
 * Fetches all teams.
 * @returns Promise<Team[]> An array of teams.
 */
const getTeams = async (): Promise<Team[]> => {
    try {
        const response = await apiClient.get<Team[]>('/api/teams/index');
        console.log('Teams fetched:', response.data);
        return response.data;
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error('Failed to fetch teams:', axiosError.response?.data || axiosError.message);
        throw error;
    }
};

/**
 * Fetches a single team by its ID.
 * @param teamId The ID of the team to fetch.
 * @returns Promise<Team | null> The team data or null if not found.
 */
const getTeamById = async (teamId: number): Promise<Team | null> => {
    try {
        const response = await apiClient.get<Team>(`/api/teams/${teamId}`);
        console.log('Team fetched:', response.data);
        return response.data;
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error(`Failed to fetch team ${teamId}:`, axiosError.response?.data || axiosError.message);
        if (axiosError.response?.status === 404) {
            console.log(`Team ${teamId} not found.`);
            return null;
        }
        throw error;
    }
};

/**
 * Creates a new team.
 * @param payload The data for the new team (matching NewTeamPayload).
 * @returns Promise<Team> The newly created team data from the API.
 */
const createTeam = async (payload: NewTeamPayload): Promise<Team> => {
    const xsrfToken = Cookies.get('XSRF-TOKEN');
    try {
        console.log('Payload for creating team:', payload); // Debug log
        const response = await apiClient.post<Team>('/api/teams/store', payload, {
            headers: { 'X-XSRF-TOKEN': xsrfToken || '' },
        });
        console.log('Team created:', response.data);
        return response.data;
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error('Failed to create team:', axiosError.response?.data || axiosError.message);
        throw error;
    }
};

/**
 * Updates an existing team.
 * @param teamId The ID of the team to update.
 * @param payload The data to update (matching UpdateTeamPayload).
 * @returns Promise<Team> The updated team data from the API.
 */
const updateTeam = async (teamId: number, payload: UpdateTeamPayload): Promise<Team> => {
    try {
        const response = await apiClient.put<Team>(`/api/teams/${teamId}`, payload);
        console.log(`Team ${teamId} updated:`, response.data);
        return response.data;
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error(`Failed to update team ${teamId}:`, axiosError.response?.data || axiosError.message);
        throw error;
    }
};

/**
 * Deletes a team by its ID.
 * @param teamId The ID of the team to delete.
 * @returns Promise<void>
 */
const deleteTeam = async (teamId: number): Promise<void> => {
    try {
        await apiClient.delete(`/api/teams/${teamId}/destroy`);
        console.log('Team deleted:', teamId);
    } catch (error) {
        const axiosError = error as AxiosError<ApiError>;
        console.error(`Failed to delete team ${teamId}:`, axiosError.response?.data || axiosError.message);
        throw error;
    }
};

// --- Exports ---

export const authService = {
  getCsrfCookie,

};


// --- Export Task Service ---

// --- Export Team Service ---
export const teamService = {
    getTeams,
    getTeamById,
    createTeam,
    updateTeam,
    deleteTeam,
};

// Or export all combined if preferred:
// export const apiService = { ...authService, ...projectService, ...taskService, ...teamService };

